select * from "PEDIDOS" where "ID" = '4';
    select * from "CLIENTES" where "ID" = '3';
        select * from "ENDERECOS" where "ID_CLIENTE" = '3';

    select * from "ITENS_PEDIDO" where "ID_PEDIDO" = '4';
        select * from "PRODUTOS" where "ID" in (select "ID_PRODUTO" from "ITENS_PEDIDO" where "ID_PEDIDO" = '4');
            select * from "CATEGORIAS" where "ID" in (select "ID_CATEGORIA" from "PRODUTOS" where "ID" in (select "ID_PRODUTO" from "ITENS_PEDIDO" where "ID_PEDIDO" = '4'));



select "PEDIDOS"."ID",
       "PEDIDOS"."NUMERO",
       "PEDIDOS"."ID_CLIENTE",
       "PEDIDOS"."DATA_PEDIDO",
       "PEDIDOS"."VALOR_TOTAL",
       "PEDIDOS"."STATUS",
       "PEDIDOS"."OBSERVACOES",
       "CLIENTES"."ID" "CLIENTES_ID",
       "CLIENTES"."NOME" "CLIENTES_NOME",
       "CLIENTES"."EMAIL" "CLIENTES_EMAIL",
       "CLIENTES"."TELEFONE" "CLIENTES_TELEFONE",
       "CLIENTES"."CPF" "CLIENTES_CPF",
       "CLIENTES"."DATA_CADASTRO" "CLIENTES_DATA_CADASTRO",
       "CLIENTES"."ATIVO" "CLIENTES_ATIVO",
       "ENDERECOS"."ID" "ENDERECOS_ID",
       "ENDERECOS"."ID_CLIENTE" "ENDERECOS_ID_CLIENTE",
       "ENDERECOS"."RUA" "ENDERECOS_RUA",
       "ENDERECOS"."NUMERO" "ENDERECOS_NUMERO",
       "ENDERECOS"."COMPLEMENTO" "ENDERECOS_COMPLEMENTO",
       "ENDERECOS"."BAIRRO" "ENDERECOS_BAIRRO",
       "ENDERECOS"."CIDADE" "ENDERECOS_CIDADE",
       "ENDERECOS"."ESTADO" "ENDERECOS_ESTADO",
       "ENDERECOS"."CEP" "ENDERECOS_CEP",
       "ENDERECOS"."TIPO" "ENDERECOS_TIPO",
       "ITENS_PEDIDO"."ID" "ITENS_PEDIDO_ID",
       "ITENS_PEDIDO"."ID_PEDIDO" "ITENS_PEDIDO_ID_PEDIDO",
       "ITENS_PEDIDO"."ID_PRODUTO" "ITENS_PEDIDO_ID_PRODUTO",
       "ITENS_PEDIDO"."QUANTIDADE" "ITENS_PEDIDO_QUANTIDADE",
       "ITENS_PEDIDO"."VALOR_UNITARIO" "ITENS_PEDIDO_VALOR_UNITARIO",
       "ITENS_PEDIDO"."DESCONTO" "ITENS_PEDIDO_DESCONTO",
       "PRODUTOS"."ID" "PRODUTOS_ID",
       "PRODUTOS"."CODIGO" "PRODUTOS_CODIGO",
       "PRODUTOS"."NOME" "PRODUTOS_NOME",
       "PRODUTOS"."DESCRICAO" "PRODUTOS_DESCRICAO",
       "PRODUTOS"."PRECO" "PRODUTOS_PRECO",
       "PRODUTOS"."ESTOQUE" "PRODUTOS_ESTOQUE",
       "PRODUTOS"."ID_CATEGORIA" "PRODUTOS_ID_CATEGORIA",
       "PRODUTOS"."ATIVO" "PRODUTOS_ATIVO"
  from "PEDIDOS"
  left join "CLIENTES"
    on "PEDIDOS"."ID_CLIENTE" = "CLIENTES"."ID"
  left join "ENDERECOS"
    on "CLIENTES"."ID" = "ENDERECOS"."ID_CLIENTE"
  left join "ITENS_PEDIDO"
    on "PEDIDOS"."ID" = "ITENS_PEDIDO"."ID_PEDIDO"
  left join "PRODUTOS"
    on "ITENS_PEDIDO"."ID_PRODUTO" = "PRODUTOS"."ID"
 where "PEDIDOS"."ID" = '5';



SELECT "CLIENTES"."ID", "CLIENTES"."NOME", "CLIENTES"."EMAIL", "CLIENTES"."TELEFONE", "CLIENTES"."CPF", "CLIENTES"."DATA_CADASTRO", "CLIENTES"."ATIVO", "PEDIDOS"."ID" "PEDIDOS_ID", "PEDIDOS"."NUMERO" "PEDIDOS_NUMERO", "PEDIDOS"."ID_CLIENTE" "PEDIDOS_ID_CLIENTE", "PEDIDOS"."DATA_PEDIDO" "PEDIDOS_DATA_PEDIDO", "PEDIDOS"."VALOR_TOTAL" "PEDIDOS_VALOR_TOTAL", "PEDIDOS"."STATUS" "PEDIDOS_STATUS", "PEDIDOS"."OBSERVACOES" "PEDIDOS_OBSERVACOES", "ITENS_PEDIDO"."ID" "ITENS_PEDIDO_ID", "ITENS_PEDIDO"."ID_PEDIDO" "ITENS_PEDIDO_ID_PEDIDO", "ITENS_PEDIDO"."ID_PRODUTO" "ITENS_PEDIDO_ID_PRODUTO", "ITENS_PEDIDO"."QUANTIDADE" "ITENS_PEDIDO_QUANTIDADE", "ITENS_PEDIDO"."VALOR_UNITARIO" "ITENS_PEDIDO_VALOR_UNITARIO", "ITENS_PEDIDO"."DESCONTO" "ITENS_PEDIDO_DESCONTO", "PRODUTOS"."ID" "PRODUTOS_ID", "PRODUTOS"."CODIGO" "PRODUTOS_CODIGO", "PRODUTOS"."NOME" "PRODUTOS_NOME", "PRODUTOS"."DESCRICAO" "PRODUTOS_DESCRICAO", "PRODUTOS"."PRECO" "PRODUTOS_PRECO", "PRODUTOS"."ESTOQUE" "PRODUTOS_ESTOQUE", "PRODUTOS"."ID_CATEGORIA" "PRODUTOS_ID_CATEGORIA", "PRODUTOS"."ATIVO" "PRODUTOS_ATIVO", "ENDERECOS"."ID" "ENDERECOS_ID", "ENDERECOS"."ID_CLIENTE" "ENDERECOS_ID_CLIENTE", "ENDERECOS"."RUA" "ENDERECOS_RUA", "ENDERECOS"."NUMERO" "ENDERECOS_NUMERO", "ENDERECOS"."COMPLEMENTO" "ENDERECOS_COMPLEMENTO", "ENDERECOS"."BAIRRO" "ENDERECOS_BAIRRO", "ENDERECOS"."CIDADE" "ENDERECOS_CIDADE", "ENDERECOS"."ESTADO" "ENDERECOS_ESTADO", "ENDERECOS"."CEP" "ENDERECOS_CEP", "ENDERECOS"."TIPO" "ENDERECOS_TIPO" FROM "CLIENTES"
LEFT JOIN "PEDIDOS" ON "CLIENTES"."ID" = "PEDIDOS"."ID_CLIENTE"
LEFT JOIN "ITENS_PEDIDO" ON "PEDIDOS"."ID" = "ITENS_PEDIDO"."ID_PEDIDO"
LEFT JOIN "PRODUTOS" ON "ITENS_PEDIDO"."ID_PRODUTO" = "PRODUTOS"."ID"
LEFT JOIN "ENDERECOS" ON "CLIENTES"."ID" = "ENDERECOS"."ID_CLIENTE";
