


CREATE TABLE CATEGORIAS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME        VARCHAR2(100) NOT NULL,
    DESCRICAO   VARCHAR2(500),
    ATIVO       NUMBER(1) DEFAULT 1 NOT NULL
);

COMMENT ON TABLE CATEGORIAS IS 'Categorias de produtos';
COMMENT ON COLUMN CATEGORIAS.ID IS 'Identificador único da categoria';
COMMENT ON COLUMN CATEGORIAS.NOME IS 'Nome da categoria';
COMMENT ON COLUMN CATEGORIAS.DESCRICAO IS 'Descrição da categoria';
COMMENT ON COLUMN CATEGORIAS.ATIVO IS 'Categoria ativa (1) ou inativa (0)';

-- Dados de exemplo
INSERT INTO CATEGORIAS (NOME, DESCRICAO) VALUES ('Eletrônicos', 'Produtos eletrônicos e tecnologia');
INSERT INTO CATEGORIAS (NOME, DESCRICAO) VALUES ('Livros', 'Livros físicos e digitais');
INSERT INTO CATEGORIAS (NOME, DESCRICAO) VALUES ('Roupas', 'Vestuário masculino e feminino');
INSERT INTO CATEGORIAS (NOME, DESCRICAO) VALUES ('Alimentos', 'Alimentos e bebidas');
INSERT INTO CATEGORIAS (NOME, DESCRICAO) VALUES ('Móveis', 'Móveis e decoração');

-- ============================================
-- 2. CLIENTES (sem dependências)
-- ============================================

CREATE TABLE CLIENTES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME            VARCHAR2(200) NOT NULL,
    EMAIL           VARCHAR2(200) UNIQUE NOT NULL,
    TELEFONE        VARCHAR2(20),
    CPF             VARCHAR2(14) UNIQUE NOT NULL,
    DATA_CADASTRO   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ATIVO           NUMBER(1) DEFAULT 1 NOT NULL
);

COMMENT ON TABLE CLIENTES IS 'Cadastro de clientes do sistema';
COMMENT ON COLUMN CLIENTES.ID IS 'Identificador único do cliente';
COMMENT ON COLUMN CLIENTES.NOME IS 'Nome completo do cliente';
COMMENT ON COLUMN CLIENTES.EMAIL IS 'E-mail para contato';
COMMENT ON COLUMN CLIENTES.TELEFONE IS 'Telefone principal';
COMMENT ON COLUMN CLIENTES.CPF IS 'CPF do cliente';
COMMENT ON COLUMN CLIENTES.DATA_CADASTRO IS 'Data de registro no sistema';
COMMENT ON COLUMN CLIENTES.ATIVO IS 'Cliente ativo (1) ou inativo (0)';

-- Índices
CREATE INDEX IDX_CLIENTES_EMAIL ON CLIENTES(EMAIL);
CREATE INDEX IDX_CLIENTES_CPF ON CLIENTES(CPF);

-- Dados de exemplo
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CPF) VALUES ('João Silva', 'joao.silva@email.com', '(11) 98765-4321', '123.456.789-00');
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CPF) VALUES ('Maria Santos', 'maria.santos@email.com', '(11) 98765-4322', '987.654.321-00');
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CPF) VALUES ('Pedro Oliveira', 'pedro.oliveira@email.com', '(11) 98765-4323', '456.789.123-00');
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CPF) VALUES ('Ana Costa', 'ana.costa@email.com', '(11) 98765-4324', '321.654.987-00');
INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE, CPF) VALUES ('Carlos Souza', 'carlos.souza@email.com', '(11) 98765-4325', '789.123.456-00');

-- ============================================
-- 3. ENDERECOS (depende de CLIENTES)
-- ============================================

CREATE TABLE ENDERECOS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE      NUMBER NOT NULL,
    RUA             VARCHAR2(200) NOT NULL,
    NUMERO          VARCHAR2(20) NOT NULL,
    COMPLEMENTO     VARCHAR2(100),
    BAIRRO          VARCHAR2(100) NOT NULL,
    CIDADE          VARCHAR2(100) NOT NULL,
    ESTADO          VARCHAR2(2) NOT NULL,
    CEP             VARCHAR2(10) NOT NULL,
    TIPO            VARCHAR2(20) DEFAULT 'RESIDENCIAL' NOT NULL,
    CONSTRAINT FK_ENDERECOS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
    CONSTRAINT CK_ENDERECOS_TIPO CHECK (TIPO IN ('RESIDENCIAL', 'COMERCIAL', 'ENTREGA'))
);

COMMENT ON TABLE ENDERECOS IS 'Endereços dos clientes';
COMMENT ON COLUMN ENDERECOS.ID IS 'Identificador único do endereço';
COMMENT ON COLUMN ENDERECOS.ID_CLIENTE IS 'Referência ao cliente';
COMMENT ON COLUMN ENDERECOS.RUA IS 'Nome da rua';
COMMENT ON COLUMN ENDERECOS.NUMERO IS 'Número do endereço';
COMMENT ON COLUMN ENDERECOS.COMPLEMENTO IS 'Complemento (apto, bloco, etc)';
COMMENT ON COLUMN ENDERECOS.BAIRRO IS 'Bairro';
COMMENT ON COLUMN ENDERECOS.CIDADE IS 'Cidade';
COMMENT ON COLUMN ENDERECOS.ESTADO IS 'UF do estado';
COMMENT ON COLUMN ENDERECOS.CEP IS 'CEP';
COMMENT ON COLUMN ENDERECOS.TIPO IS 'Tipo de endereço (RESIDENCIAL, COMERCIAL, ENTREGA)';

-- Índices
CREATE INDEX IDX_ENDERECOS_CLIENTE ON ENDERECOS(ID_CLIENTE);

-- Dados de exemplo (usando IDs dos clientes inseridos)
INSERT INTO ENDERECOS (ID_CLIENTE, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, TIPO)
VALUES (1, 'Rua das Flores', '123', 'Centro', 'São Paulo', 'SP', '01234-567', 'RESIDENCIAL');

INSERT INTO ENDERECOS (ID_CLIENTE, RUA, NUMERO, COMPLEMENTO, BAIRRO, CIDADE, ESTADO, CEP, TIPO)
VALUES (1, 'Av. Paulista', '1000', 'Sala 501', 'Bela Vista', 'São Paulo', 'SP', '01310-100', 'COMERCIAL');

INSERT INTO ENDERECOS (ID_CLIENTE, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, TIPO)
VALUES (2, 'Rua Augusta', '456', 'Consolação', 'São Paulo', 'SP', '01305-000', 'RESIDENCIAL');

INSERT INTO ENDERECOS (ID_CLIENTE, RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP, TIPO)
VALUES (3, 'Rua Oscar Freire', '789', 'Jardins', 'São Paulo', 'SP', '01426-001', 'RESIDENCIAL');

-- ============================================
-- 4. PRODUTOS (depende de CATEGORIAS)
-- ============================================

CREATE TABLE PRODUTOS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO          VARCHAR2(50) UNIQUE NOT NULL,
    NOME            VARCHAR2(200) NOT NULL,
    DESCRICAO       VARCHAR2(1000),
    PRECO           NUMBER(10,2) NOT NULL,
    ESTOQUE         NUMBER(10) DEFAULT 0 NOT NULL,
    ID_CATEGORIA    NUMBER NOT NULL,
    ATIVO           NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_PRODUTOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID),
    CONSTRAINT CK_PRODUTOS_PRECO CHECK (PRECO >= 0),
    CONSTRAINT CK_PRODUTOS_ESTOQUE CHECK (ESTOQUE >= 0)
);

COMMENT ON TABLE PRODUTOS IS 'Catálogo de produtos disponíveis para venda';
COMMENT ON COLUMN PRODUTOS.ID IS 'Identificador único do produto';
COMMENT ON COLUMN PRODUTOS.CODIGO IS 'Código SKU do produto';
COMMENT ON COLUMN PRODUTOS.NOME IS 'Nome do produto';
COMMENT ON COLUMN PRODUTOS.DESCRICAO IS 'Descrição detalhada do produto';
COMMENT ON COLUMN PRODUTOS.PRECO IS 'Preço unitário';
COMMENT ON COLUMN PRODUTOS.ESTOQUE IS 'Quantidade em estoque';
COMMENT ON COLUMN PRODUTOS.ID_CATEGORIA IS 'Categoria do produto';
COMMENT ON COLUMN PRODUTOS.ATIVO IS 'Produto ativo (1) ou inativo (0)';

-- Índices
CREATE INDEX IDX_PRODUTOS_CODIGO ON PRODUTOS(CODIGO);
CREATE INDEX IDX_PRODUTOS_CATEGORIA ON PRODUTOS(ID_CATEGORIA);

-- Dados de exemplo
INSERT INTO PRODUTOS (CODIGO, NOME, DESCRICAO, PRECO, ESTOQUE, ID_CATEGORIA)
VALUES ('ELET001', 'Notebook Dell Inspiron', 'Notebook i5, 8GB RAM, 256GB SSD', 3499.99, 15, 1);

INSERT INTO PRODUTOS (CODIGO, NOME, DESCRICAO, PRECO, ESTOQUE, ID_CATEGORIA)
VALUES ('ELET002', 'Mouse Logitech MX Master', 'Mouse sem fio ergonômico', 399.90, 50, 1);

INSERT INTO PRODUTOS (CODIGO, NOME, DESCRICAO, PRECO, ESTOQUE, ID_CATEGORIA)
VALUES ('LIV001', 'Clean Code - Robert Martin', 'Livro sobre código limpo', 89.90, 30, 2);

INSERT INTO PRODUTOS (CODIGO, NOME, DESCRICAO, PRECO, ESTOQUE, ID_CATEGORIA)
VALUES ('ROUP001', 'Camiseta Básica Preta', 'Camiseta 100% algodão', 49.90, 100, 3);

INSERT INTO PRODUTOS (CODIGO, NOME, DESCRICAO, PRECO, ESTOQUE, ID_CATEGORIA)
VALUES ('ELET003', 'Teclado Mecânico RGB', 'Teclado gamer switches blue', 599.90, 25, 1);

INSERT INTO PRODUTOS (CODIGO, NOME, DESCRICAO, PRECO, ESTOQUE, ID_CATEGORIA)
VALUES ('LIV002', 'Domain-Driven Design - Eric Evans', 'Livro sobre DDD', 125.00, 10, 2);

INSERT INTO PRODUTOS (CODIGO, NOME, DESCRICAO, PRECO, ESTOQUE, ID_CATEGORIA)
VALUES ('MOV001', 'Cadeira Gamer Preta', 'Cadeira ergonômica com apoio lombar', 899.00, 8, 5);

-- ============================================
-- 5. PEDIDOS (depende de CLIENTES)
-- ============================================

CREATE TABLE PEDIDOS (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO          VARCHAR2(50) UNIQUE NOT NULL,
    ID_CLIENTE      NUMBER NOT NULL,
    DATA_PEDIDO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VALOR_TOTAL     NUMBER(10,2) DEFAULT 0 NOT NULL,
    STATUS          VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL,
    OBSERVACOES     VARCHAR2(1000),
    CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
    CONSTRAINT CK_PEDIDOS_STATUS CHECK (STATUS IN ('PENDENTE', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO')),
    CONSTRAINT CK_PEDIDOS_VALOR CHECK (VALOR_TOTAL >= 0)
);

COMMENT ON TABLE PEDIDOS IS 'Pedidos realizados pelos clientes';
COMMENT ON COLUMN PEDIDOS.ID IS 'Identificador único do pedido';
COMMENT ON COLUMN PEDIDOS.NUMERO IS 'Número do pedido';
COMMENT ON COLUMN PEDIDOS.ID_CLIENTE IS 'Referência ao cliente';
COMMENT ON COLUMN PEDIDOS.DATA_PEDIDO IS 'Data de realização do pedido';
COMMENT ON COLUMN PEDIDOS.VALOR_TOTAL IS 'Valor total do pedido';
COMMENT ON COLUMN PEDIDOS.STATUS IS 'Status atual (PENDENTE, PAGO, ENVIADO, ENTREGUE, CANCELADO)';
COMMENT ON COLUMN PEDIDOS.OBSERVACOES IS 'Observações adicionais';

-- Índices
CREATE INDEX IDX_PEDIDOS_CLIENTE ON PEDIDOS(ID_CLIENTE);
CREATE INDEX IDX_PEDIDOS_STATUS ON PEDIDOS(STATUS);
CREATE INDEX IDX_PEDIDOS_DATA ON PEDIDOS(DATA_PEDIDO);

-- Dados de exemplo
INSERT INTO PEDIDOS (NUMERO, ID_CLIENTE, VALOR_TOTAL, STATUS)
VALUES ('PED-2025-001', 1, 3949.88, 'PAGO');

INSERT INTO PEDIDOS (NUMERO, ID_CLIENTE, VALOR_TOTAL, STATUS)
VALUES ('PED-2025-002', 2, 89.90, 'ENVIADO');

INSERT INTO PEDIDOS (NUMERO, ID_CLIENTE, VALOR_TOTAL, STATUS)
VALUES ('PED-2025-003', 1, 599.90, 'ENTREGUE');

INSERT INTO PEDIDOS (NUMERO, ID_CLIENTE, VALOR_TOTAL, STATUS)
VALUES ('PED-2025-004', 3, 1498.90, 'PENDENTE');

INSERT INTO PEDIDOS (NUMERO, ID_CLIENTE, VALOR_TOTAL, STATUS)
VALUES ('PED-2025-005', 4, 125.00, 'PAGO');

-- ============================================
-- 6. ITENS_PEDIDO (depende de PEDIDOS e PRODUTOS)
-- ============================================

CREATE TABLE ITENS_PEDIDO (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PEDIDO           NUMBER NOT NULL,
    ID_PRODUTO          NUMBER NOT NULL,
    QUANTIDADE          NUMBER(10) NOT NULL,
    VALOR_UNITARIO      NUMBER(10,2) NOT NULL,
    DESCONTO            NUMBER(10,2) DEFAULT 0,
    CONSTRAINT FK_ITENS_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID),
    CONSTRAINT FK_ITENS_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID),
    CONSTRAINT CK_ITENS_QUANTIDADE CHECK (QUANTIDADE > 0),
    CONSTRAINT CK_ITENS_VALOR CHECK (VALOR_UNITARIO >= 0),
    CONSTRAINT CK_ITENS_DESCONTO CHECK (DESCONTO >= 0)
);

COMMENT ON TABLE ITENS_PEDIDO IS 'Itens que compõem cada pedido';
COMMENT ON COLUMN ITENS_PEDIDO.ID IS 'Identificador único do item';
COMMENT ON COLUMN ITENS_PEDIDO.ID_PEDIDO IS 'Referência ao pedido';
COMMENT ON COLUMN ITENS_PEDIDO.ID_PRODUTO IS 'Referência ao produto';
COMMENT ON COLUMN ITENS_PEDIDO.QUANTIDADE IS 'Quantidade do produto';
COMMENT ON COLUMN ITENS_PEDIDO.VALOR_UNITARIO IS 'Valor unitário no momento da compra';
COMMENT ON COLUMN ITENS_PEDIDO.DESCONTO IS 'Desconto aplicado ao item';

-- Índices
CREATE INDEX IDX_ITENS_PEDIDO ON ITENS_PEDIDO(ID_PEDIDO);
CREATE INDEX IDX_ITENS_PRODUTO ON ITENS_PEDIDO(ID_PRODUTO);

-- Dados de exemplo (PED-2025-001 = João Silva)
INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO, DESCONTO)
VALUES (1, 1, 1, 3499.99, 50.00); -- Notebook Dell

INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO)
VALUES (1, 2, 1, 399.90); -- Mouse Logitech

INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO, DESCONTO)
VALUES (1, 5, 1, 599.90, 499.91); -- Teclado Mecânico (com desconto)

-- PED-2025-002 = Maria Santos
INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO)
VALUES (2, 3, 1, 89.90); -- Clean Code

-- PED-2025-003 = João Silva
INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO)
VALUES (3, 5, 1, 599.90); -- Teclado Mecânico

-- PED-2025-004 = Pedro Oliveira
INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO)
VALUES (4, 5, 2, 599.90); -- 2x Teclado Mecânico

INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO)
VALUES (4, 2, 1, 399.90); -- Mouse Logitech

INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO, DESCONTO)
VALUES (4, 4, 2, 49.90, 10.00); -- 2x Camisetas

-- PED-2025-005 = Ana Costa
INSERT INTO ITENS_PEDIDO (ID_PEDIDO, ID_PRODUTO, QUANTIDADE, VALOR_UNITARIO)
VALUES (5, 6, 1, 125.00); -- DDD Book

COMMIT;

-- ============================================
-- 7. CONSULTAS DE VERIFICAÇÃO
-- ============================================

select * from CLIENTES;
select * from ENDERECOS;
select * from CATEGORIAS;
select * from PRODUTOS;
select * from PEDIDOS;
select * from ITENS_PEDIDO;
